from .paths import DEFAULT_ASSETS_DIR


ASSETS_DIR = DEFAULT_ASSETS_DIR
WINDOWS = []
CONTROL_PANEL = None
TRAY_ICON = None
EXITING = False
RESTORING_SESSION = False
CONFIG_WARNINGS = []
RECENT_DIAGNOSTICS = []
PRESERVED_WINDOW_CONFIGS = []
UI_CONFIG = {}
