from .paths import DEFAULT_ASSETS_DIR


ASSETS_DIR = DEFAULT_ASSETS_DIR
WINDOWS = []
CONTROL_PANEL = None
TRAY_ICON = None
EXITING = False
RESTORING_SESSION = False
CONFIG_WARNINGS = []
RECENT_DIAGNOSTICS = []
PRESERVED_WINDOW_CONFIGS = []
UI_CONFIG = {}
LOCAL_API_CONFIG = {"enabled": False, "token": ""}
LOCAL_API_SERVER = None
LOCAL_API_DISPATCHER = None
LOCAL_API_EVENTS = []
LOCAL_API_OVERLAY_CREATED_AT = {}
LOCAL_API_NEXT_RUNTIME_ID = 1
