from .models import AssetType


SUPPORTED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}
SUPPORTED_ANIMATED_IMAGE_EXTENSIONS = {".gif", ".apng"}
SUPPORTED_VIDEO_EXTENSIONS = {".webm"}
SUPPORTED_ASSET_EXTENSIONS = SUPPORTED_IMAGE_EXTENSIONS | SUPPORTED_ANIMATED_IMAGE_EXTENSIONS | SUPPORTED_VIDEO_EXTENSIONS
DEFAULT_FRAME_FPS = 12
METADATA_ASSET_TYPES = {
    AssetType.FRAME_ANIMATION,
    AssetType.SPRITE_STRIP,
    AssetType.SPRITESHEET,
    AssetType.COMPOSITE_UI,
}
